import Header from "@/components/layout/header";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto_Slab } from "next/font/google";
import Footer from "@/components/layout/footer";
const robotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Panaverse Dao",
  description: "Generated by React.js and Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={robotoSlab.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}